### ISSUE TITLE
Bug in argument check (metrics)

### ISSUE THREAD

**Issue by PhMueller** [automl/jahs_bench_201#14]
Hi guys, 

thanks for the awesome work. 

While using it, the line below throws an error, when `metrics` is specified. 

https://github.com/automl/jahs_bench_201/blob/e9a93ade6cd80028b45d46e15de2cd96574a9662/jahs_bench/api.py#L108

I think it should be 
``` 
unknown = metrics - set(self.__known_metrics)  
```
instead.

Cheers, Philipp

**Comment by eddiebergman** [comment]
You're right :) I erroneously made this change before but the merged PR should fix it :)
