### ISSUE TITLE
Wrong path when loading tabular data

### ISSUE THREAD

**Issue by PhMueller** [automl/jahs_bench_201#16]
hi guys, 

loading the tabular data throws an error. 

I think the problem is here: 

https://github.com/automl/jahs_bench_201/blob/b9232f301f7fd659a85445bf65d29025ef84ef7d/jahs_bench/api.py#L162-L165

`self.data_dir` should be `self.table_dir`:

```
 def _load_table(self): 
     assert self.table_dir.exists() and self.table_dir.is_dir() 
  
     table_path = self.table_dir / self.task.value 
```

Thanks in advance, 
cheers.

**Comment by eddiebergman** [comment]
I appreciate all your findings and the solutions :)

**Comment by PhMueller** [comment]
Wow, that was quick! :-) 
Thanks a lot for your work!
