### ISSUE TITLE
Provide a fixed tag version once stable 

### ISSUE THREAD

**Issue by eddiebergman** [automl/jahs_bench_201#2]
Not sure if the benchmark is stable yet but having a tag to version of would be ideal.

It would also be good to provide an option in the `download` module rather then to use fixed versioned surrogates/data once possible:
https://github.com/automl/jahs_bench_201/blob/c1e92dd92a0c4906575c4e3e4ee9e7420efca5f1/jahs_bench/download.py#L5-L6

**Comment by NeoChaos12** [comment]
This is indeed a feature that we have planned but must hold off on until our hosting has been stabilized. I'll keep this issue updated!

**Comment by NeoChaos12** [comment]
After revisiting this issue, we have decided that we will drop this feature once the final data and models have been uploaded to Figshare since there will be no further updates to the links after that.
